name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: mysql
            experimental: false
          - mediawiki_version: 1.36
            database_type: mysql
            experimental: true
          - mediawiki_version: 1.37
            database_type: mysql
            experimental: true

    container:
      image: mediawiki:${{ matrix.mediawiki_version }}
      options: --link some-${{ matrix.database_type }}:${{ matrix.database_type }}

    env:
      EXT_NAME: SemanticOrganization
      DB_ROOT_PWD: database
      MW_DB_TYPE: ${{ matrix.database_type }}
      MW_DB_SERVER: ${{ matrix.database_type }}
      MW_EXT_PATH: /var/www/html/extensions

    services:
      some-mysql:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_ROOT_PWD }}

    steps:
      - name: Checkout Extension
        uses: actions/checkout@v2
        with:
          repository: hexmode/${{ env.EXT_NAME }}
          path: ${{ env.EXT_NAME }}

      - name: Symlink extension
        run: |
          mkdir -p ${{ env.MW_EXT_PATH }}
          ln -s `pwd`/${{ env.EXT_NAME }}                                      \
            ${{ env.MW_EXT_PATH }}/${{ env.EXT_NAME }}
          ls -ld ${{ env.MW_EXT_PATH }}/${{ env.EXT_NAME }}

      - name: Get Composer
        run: |
          cd ${{ env.EXT_NAME }}
          make getComposer

      - name: MediaWiki Composer Update
        run: |
          cd ${{ env.EXT_NAME }}
          make mediaWikiComposerUpdate

      - name: MediaWiki Install
        run: |
          cd ${{ env.EXT_NAME }}
          make mediaWikiInstall

      - name: Enable Debug Output
        run: |
          cd ${{ env.EXT_NAME }}
          make enableDebugOutput

      - name: Install SemanticMediaWiki
        run: |
          cd ${{ env.EXT_NAME }}
          make installSemanticMediaWiki

      - name: Run Tests
        run: |
          cd ${{ env.EXT_NAME }}
          make ci
